### ISSUE TITLE
Housenumbers not showing 

### ISSUE THREAD

**Issue by assaka** [experius/Magento-2-Module-Experius-Postcode-NL#10]
When you enter a zipcode and housenumber, the housenumber is not shown in the payment method step.
In form/element/postcode.js:257,  you have to cast response.houseNumber to a string for it to appear.

registry.get(self.parentName + '.street.1').set('value',response.houseNumber.toString()).set('error',false);

**Comment by dheesbeen** [comment]
Thanks for sharing! Solved
