### ISSUE TITLE
Incorrect dependency in class Experius\Postcode\Block\Checkout\LayoutProcessor

### ISSUE THREAD

**Issue by robbertstevens** [experius/Magento-2-Module-Experius-Postcode-NL#11]
Incorrect dependency in class `Experius\Postcode\Block\Checkout\LayoutProcessor` in `home/experius/domains/geneeskundeboek.nl.local01.xpdev.nl/vendor/experius/module-postcode/Block/Checkout/LayoutProcessor.php`

`\Magento\Framework\App\Config\ScopeConfigInterface` already exists in context object
`\Psr\Log\LoggerInterface` already exists in context object

Omdat je `\Magento\Framework\View\Element\AbstractBlock` extend bestaan deze properties al en hoef je ze dus niet meer te DIen.

Als je compiled krijg je deze error.

**Comment by dheesbeen** [comment]
Thanks! solved
