### ISSUE TITLE
Weird Firefox bug on checkout page

### ISSUE THREAD

**Issue by rakibabu** [experius/Magento-2-Module-Experius-Postcode-NL#18]
Hi,

On the checkout page in Firefox there is a weird bug. The checkout page doesn't load and in the console I get this errors:

```
TypeError: this.source is undefined 51 errors postcode.js line 118:17
```

Reference to this file: `experius/module-postcode/view/frontend/web/js/view/form/postcode.js`

```javascript
var formData = this.source.get(this.customerScope);
```

This problem only occurs in firefox, in Safari, Chrome and IE > 11 it's working fine.
What is this error and how to fix this?

Kind regards,

Rakhal Imming

**Comment by patrick-bigbridge** [comment]
We have a similar problem: checkout page hangs with loader icon in center.

The javascript error is:

this.source is undefined

and occurs on line 32 of experius/module-postcode/view/frontend/web/js/view/form/postcode.js

The problem does not only occur in Firefox / Ubuntu (see screenshot)
![screenshot from 2017-07-06 13-03-45](https://user-images.githubusercontent.com/17122199/27908347-982e080e-624b-11e7-9d3c-9f51f4ffdf37.png)

but also on Edge / Windows 10

**Comment by dheesbeen** [comment]
I see some strange behaviour in Firefox. Let you know when its fixed

**Comment by wallie85** [comment]
Hi dheesbeen,

is there already an update or fix on this one?

Thanks

**Comment by dheesbeen** [comment]
@wallie85 Did you allready update? This friday a new version was released with some changes in the javascript. I just placed some testorders in firefox. Seems to work fine. Let me know!

**Comment by wallie85** [comment]
@dheesbeen not yet so thanks for the update! overlooked that there was a new version and expected an update here. We will update the module!

**Comment by patrick-bigbridge** [comment]
The fix works for Firefox / Ubuntu, but unfortunately not for Edge / Windows. I add a new screenshot.
![nkkahfehjafjpmcf](https://user-images.githubusercontent.com/17122199/28122638-0b17c102-671f-11e7-91d7-f69913abd94e.png)

**Comment by wallie85** [comment]
@dheesbeen for us the fix in Firefox does not seem to work. What I see is that the first time that you visit the page /checkout/ is working fine, you can also pay. But when you are at the page and you reload the page or shop further it does show a white page as shown below.

How can we fix this?

![schermafbeelding 2017-07-13 om 10 16 04](https://user-images.githubusercontent.com/30111255/28156836-9d9d2234-67b4-11e7-99b3-8fcc771155c5.png)

**Comment by wallie85** [comment]
@dheesbeen Did you in any change already have a look at the returning problem with reloading and shopping further?

**Comment by krukas** [comment]
For me the problem occurs in Chrome and Firefox, but only when you have 'Enable JavaScript Bundling' enabled.

**Comment by wallie85** [comment]
@dheesbeen Can you give an update on this issue?

**Comment by ashar01** [comment]
i have same issue after advanced javascript bundling. did anyone find solution ? seems like its dependency issue
