### ISSUE TITLE
Address showing [object Object] on Checkout startup.

### ISSUE THREAD

**Issue by mdesplenter** [experius/Magento-2-Module-Experius-Postcode-NL#29]
When opening the Checkout page, the (disabled) address input field shows [object Object]. Other functionality is working like it should.

**Comment by mve0991** [comment]
We run into the same problem. Any update on this issue yet?

**Comment by Tomasz-Silpion** [comment]
Up, otherwise I will fork this repo and fix it myself ;)

**Comment by dheesbeen** [comment]
@bartlubbersen Do you have time and opportunity to reproduce and test this and maybe provide us with a fix?

**Comment by AlexNauta** [comment]
Just a quick & dirty fix for now, I hope they will fix it in the future:
Add this in vendor/experius/module-postcode/view/frontend/web/js/view/form/postcode.js

Between lines 175 & 176:

`    if (registry.get(self.parentName + '.street.0').get('value') == '[object Object] ') {
					this.debug('Fixing street.0 as it contains [object Object] - only a temporary fix for now');
					registry.get(self.parentName + '.street.0').set('value', '').set('error', false);
                }`
