### ISSUE TITLE
When autocomplete is used the housenumber addition is saved in street 2 instead of street 3 

### ISSUE THREAD

**Issue by melnickforever** [experius/Magento-2-Module-Experius-Postcode-NL#31]
We have module version: 1.0.0
Magento CE 2.2.3

We 3 fields in magento address: street,  house number, house number addition

When we use current module in order in  billing and shipping address house number addition is saved in street 2 instead of street 3 

Without autocomplete module, magento works correctly.
Can you please check this?
 

![screenshot-melano-beta ism-hosting nl-2018-04-12-16-10-15](https://user-images.githubusercontent.com/310536/38679368-3d54eb2a-3e6c-11e8-8645-9e8e96ae0e32.png)
![screenshot-melano-beta ism-hosting nl-2018-04-12-16-09-30](https://user-images.githubusercontent.com/310536/38679369-3d6f5924-3e6c-11e8-942b-17f620c75ea8.png)

**Comment by melnickforever** [comment]
Have you any solution for this problem?

**Comment by experius-nl** [comment]
This has been fixed in version 1.2.1.
