### ISSUE TITLE
[object Object] is shown when entering address manually

### ISSUE THREAD

**Issue by the-line** [experius/Magento-2-Module-Experius-Postcode-NL#40]
When the option to manually add the address is selected after a address is given, the "Street" field will show "[object Object]".

It happens with 1.3.1 at least.

The following pull request should fix the problem:
https://github.com/experius/Magento-2-Module-Experius-Postcode-NL/pull/34

![Screenshot](https://user-images.githubusercontent.com/7580485/61446810-149fb700-a950-11e9-939d-1a08c47e000f.png)

**Comment by lewisvoncken** [comment]
@the-line this has been resolved in #52
