### ISSUE TITLE
Postcode not being sent if fields are autofilled incorrectly.

### ISSUE THREAD

**Issue by indykoning** [experius/Magento-2-Module-Experius-Postcode-NL#45]
When Chrome autofill is used with incorrect data, such as an invalid postcode or a housenumber with the streetname included you recieve a validation error as expected. And the original Magento postcode field is not filled.

When you then check the checkbox to manually enter your address and autofill again the Magento postcode field is still not filled. And as a result when you click next a default postcode will be entered.

A suggested change is to fill the Magento postcode field before validating the postcode.

This has been tested on Magento 2 CE 2.3.3 on onepage checkout with the latest commit on master #38f97e75d68248f59afd68a0405780d63fd5f35b

**Comment by lewisvoncken** [comment]
@indykoning this has been resolved in #52
