### ISSUE TITLE
Missing version constraint

### ISSUE THREAD

**Issue by bethlehemit** [experius/Magento-2-Module-Experius-Postcode-NL#50]
The composer.json does not provide a limit to the M2 versions supported. As such, M2.2 will update experius/module-postcode from version 1.3.4 to version 1.4, breaking the compile with the following message:
PHP Fatal error:  Interface 'Magento\Framework\GraphQl\Query\Resolver\IdentityInterface' not found in /home/ronald/SD/pauw/vendor/experius/module-postcode/Model/Resolver/Postcode/Identity.php on line 15

Could you please add a version constraint to the module?

**Comment by dheesbeen** [comment]
@Hexmage

**Comment by Hexmage** [comment]
Added a requirement for magento 2.3+ on version 1.4.0 and higher.

**Comment by bethlehemit** [comment]
Thank you very much!
