### ISSUE TITLE
Shipping Methods don't refresh

### ISSUE THREAD

**Issue by robertbuijs** [experius/Magento-2-Module-Experius-Postcode-NL#7]
When PostcodeNL returns an address, Shipping Methods should reload and retreive available shipping methods for shipping destination.

This is default Magento 2 behavior: Shipping Methods are reloaded when Shipping destination country is changed.

**Comment by peterkeijsers** [comment]
@robertbuijs en @dheesbeen 

This seems to trigger only when having entered an zip-code. When entering a zipcode you always get a Warning saying the zipcode format is invalid. This seems to block the further reloading of the shipping methods. When I leave the zipcode field empty and than change the country field (and clicking outside the country dropdown) triggers a reload of the shipping methods.
